export enum EmployeessActionTypes {
  GET_EMPLOYEES_SCHEDULED_REQUEST = 'GET_EMPLOYEES_SCHEDULED_REQUEST',
  GET_EMPLOYEES_SCHEDULED_SUCCESS = 'GET_EMPLOYEES_SCHEDULED_SUCCESS',
  GET_EMPLOYEES_SCHEDULED_ERROR = 'GET_EMPLOYEES_SCHEDULED_ERROR',
  GET_EMPLOYEES_LIST_REQUEST = 'GET_EMPLOYEES_LIST_REQUEST',
  GET_EMPLOYEES_LIST_SUCCESS = 'GET_EMPLOYEES_LIST_SUCCESS',
  GET_EMPLOYEES_LIST_ERROR = 'GET_EMPLOYEES_LIST_ERROR',

  CLEAR_LIST = 'CLEAR_LIST',
}

export interface GetEmployeesReq {
  zip: number;
  brand: string;
  type: string;
}
